title: Why, Hello There
description: >- # this means to ignore newlines until "baseurl:"

url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: collections

# Collections path
collections:
  kiddos:
    output: true
    permalink: /:collection/:name/
  work:
    output: true
    permalink: /:collection/:name/
  archive:
      output: true
      permalink: /:collection/:name/
  thoughts:
      output: true
      permalink: /:collection/:name/

# Collections default
defaults:
  - scope:
      path: ""
      type: "kiddos"
    values:
      layout: default
  - scope:
      path: ""
      type: "work"
    values:
      layout: default
  - scope:
      path: ""
      type: "archive"
    values:
      layout: default
  - scope:
      path: ""
      type: "thoughts"
    values:
      layout: default
