title: Hilarious things my kiddos say
description: >- # this means to ignore newlines until "baseurl:"
  This is my first jekyll blog and serves two purposes: 1) force myself to keep up with code by using Jekyll to power my blog and 2) capturing hilarious things my kiddos say as they get older.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Sass settings
sass:
  sass_dir: assets/stylesheets

# Collections
collections_dir: collections

# Collections path
collections:
  kiddos:
    output: true
    permalink: /:collection/:name/
  travel:
    output: true
    permalink: /:collection/:name/

# Collections default
defaults:
  - scope:
      path: ""
      type: "kiddos"
    values:
      layout: default
  - scope:
      path: ""
      type: "travel"
    values:
      layout: default
